plugins:
  - "experiment_training.components.dataloader.lerobot_data"
  - "experiment_training.components.optimizer.adamw_cosine_decay"
  - "experiment_training.components.trainer.imitation_learning.mutual_information_estimator.mutual_information_estimator_trainer"
model:
  find_unused_parameters: true
  component_config_paths:
    action_decoder: "experiment_models/mutual_information_estimator/exp1/action_decoder.yaml"
    action_encoder: "experiment_models/mutual_information_estimator/exp1/action_encoder.yaml"
    state_encoder: "experiment_models/mutual_information_estimator/exp1/state_resnet34_encoder.yaml"
    state_decoder: "experiment_models/mutual_information_estimator/exp1/state_resnet34_decoder.yaml"
  component_build_args:
    action_decoder:
      init: true
      freeze: false
    action_encoder:
      init: true
      freeze: false
    state_encoder:
      init: true
      freeze: false
    state_decoder:
      init: true
      freeze: false
  component_optims:
    action_decoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        max_lr: 5.0e-4 # OneCycleLR
        total_steps: 7660
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    action_encoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        max_lr: 5.0e-4 # OneCycleLR
        total_steps: 7660
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    state_encoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        max_lr: 5.0e-4 # OneCycleLR
        total_steps: 7660
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    state_decoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        max_lr: 5.0e-4 # OneCycleLR
        total_steps: 7660
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1

data:
  datamodule:
    type: "lerobot_dataset_factory"
    params:
      task_name: 'picknplace'
      local_files_only: false
      root: '.'
      repo_id: 'joon001001/igris-b-pnp_v3.3.2'
      action_horizon: 40
      obs_proprio_history: 40
      obs_images_history: 1
      HZ: 20
  batch_size: 512
  num_workers: 12
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 1
train:
  project_name: 'mutual_information_estimator exp1'
  epoch: 20
  load_dir: null
  save_every: 5
  save_dir: "experiment_training/imitation_learning/mutual_information_estimator/exp1"
  trainer: 
    type: 'mutual_information_estimator_trainer'
  