plugins:
  - "experiment_training.components.dataloader.lerobot_data"
  - "experiment_training.components.optimizer.adamw_cosine_decay"
  - "experiment_training.components.trainer.imitation_learning.naive_flow_matching_policy.naive_flow_matching_policy_trainer"
model:
  find_unused_parameters: true
  component_config_paths:
    backbone: "experiment_models/naive_flow_matching_policy/exp1/backbone.yaml"
    da3: "experiment_models/naive_flow_matching_policy/exp1/da3.yaml"
    proprio_projector: "experiment_models/naive_flow_matching_policy/exp1/proprio_projector.yaml"
    action_decoder: "experiment_models/naive_flow_matching_policy/exp1/action_decoder.yaml"
  component_build_args:
    backbone:
      init: false
      freeze: true
    da3:
      init: false
      freeze: true
    proprio_projector:
      init: true
      freeze: false
    action_decoder:
      init: true
      freeze: false
  component_optims:
    proprio_projector:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-9
        weight_decay: 0.01
        max_lr: 1.0e-3 # OneCycleLR
        total_steps: 1000000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    action_decoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-9
        weight_decay: 0.01
        max_lr: 1.0e-3 # OneCycleLR
        total_steps: 1000000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.01
        warmup_strategy: 'linear'
        div_factor: 25.0
        final_div_factor: 10000.0
        alpha: null
        exponent: 1.0
        last_epoch: -1

data:
  datamodule:
    type: "lerobot_dataset_factory"
    params:
      task_name: 'picknplace'
      local_files_only: false
      root: '.'
      repo_id: 'joon001001/igris-b-pnp_v3.3.2'
      action_horizon: 40
      obs_proprio_history: 40
      obs_images_history: 1
      HZ: 20
  batch_size: 32
  num_workers: 12
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 1
train:
  project_name: 'naive_flow_matching_policy exp1'
  epoch: 1000
  load_dir: null
  save_every: 3
  save_dir: "experiment_training/imitation_learning/naive_flow_matching_policy/exp1"
  trainer: 
    type: 'naive_flow_matching_policy_trainer'
  